# Generated by Django 3.2.5 on 2021-10-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_hotels_landmarks_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmarks',
            name='eng_desc',
            field=models.TextField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='landmarks',
            name='kor_desc',
            field=models.TextField(default='', max_length=600),
        ),
    ]
