# Generated by Django 3.2.5 on 2021-10-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20211014_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='star_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotels',
            name='telephone_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='english_operation_time',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='english_service_option',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='operation_time',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='service_option',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='star_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='telephone_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
